// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz3Szil-zzc7G3N89TwzGgbxBOrg3OiKM',
    appId: '1:238518563505:web:9b285da4251e5daa8ce890',
    messagingSenderId: '238518563505',
    projectId: 'sgp-4-7670a',
    authDomain: 'sgp-4-7670a.firebaseapp.com',
    storageBucket: 'sgp-4-7670a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0Xn-KQLd5YPais3qRpmBsFLKs3fGb9xo',
    appId: '1:238518563505:android:437db1b0fdd454938ce890',
    messagingSenderId: '238518563505',
    projectId: 'sgp-4-7670a',
    storageBucket: 'sgp-4-7670a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIhSho-zAWZcoZXwK1IC_wsmuqRV36uBI',
    appId: '1:238518563505:ios:5185ab5676bd7ad88ce890',
    messagingSenderId: '238518563505',
    projectId: 'sgp-4-7670a',
    storageBucket: 'sgp-4-7670a.appspot.com',
    iosClientId: '238518563505-8qbt8oo0sqokmqopnh0jobqhbudbmlnk.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIhSho-zAWZcoZXwK1IC_wsmuqRV36uBI',
    appId: '1:238518563505:ios:5a908a33cd1a177a8ce890',
    messagingSenderId: '238518563505',
    projectId: 'sgp-4-7670a',
    storageBucket: 'sgp-4-7670a.appspot.com',
    iosClientId: '238518563505-014nb37kd2k968fvt45744255kkfbvon.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
